server:
  port: 8084
spring:
  application:
    name: goods-web
  thymeleaf:
    cache: false # 开发阶段用false
  rabbitmq:
    host: 192.168.43.202
    virtual-host: /leyou
    username: leyou
    password: leyou
    connection-timeout: 1000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15