server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.43.202
    virtual-host: /leyou
    username: leyou
    password: leyou
leyou:
  sms:
    accessKeyId: LTAI4G8E2dd2Ay8UdHz5pjGX # 你自己的accessKeyId
    accessKeySecret: Ka3COO0guFGbztufoHqEmzlfgWl0Th # 你自己的AccessKeySecret
    signName: 南浔北觅 # 签名名称
    verifyCodeTemplate: SMS_209470294 # 模板名称